data = [
    # Нормальные запросы
    ("btc", "normal_request"),
    ("eth", "normal_request"),
    ("bnb", "normal_request"),
    ("usdt", "normal_request"),
    ("usdc", "normal_request"),
    ("xrp", "normal_request"),
    ("sol", "normal_request"),
    ("ada", "normal_request"),
    ("doge", "normal_request"),
    ("dot", "normal_request"),
    ("shib", "normal_request"),
    ("matic", "normal_request"),
    ("wbtc", "normal_request"),
    ("ltc", "normal_request"),
    ("uni", "normal_request"),
    ("avax", "normal_request"),
    ("chainlink", "normal_request"),
    ("algorand", "normal_request"),
    ("stellar", "normal_request"),
    ("monero", "normal_request"),
    ("aave", "normal_request"),
    ("tron", "normal_request"),
    ("iota", "normal_request"),
    ("cosmos", "normal_request"),
    ("vechain", "normal_request"),
    ("eos", "normal_request"),
    ("tezos", "normal_request"),
    ("quant", "normal_request"),
    ("hbar", "normal_request"),
    ("ftm", "normal_request"),
    ("theta", "normal_request"),
    ("zec", "normal_request"),
    ("btt", "normal_request"),
    ("chz", "normal_request"),
    ("mana", "normal_request"),
    ("sand", "normal_request"),
    ("enj", "normal_request"),
    ("hnt", "normal_request"),
    ("icp", "normal_request"),
    ("xmr", "normal_request"),
    ("dash", "normal_request"),
    ("comp", "normal_request"),
    ("yfi", "normal_request"),
    ("bat", "normal_request"),
    ("zrx", "normal_request"),
    ("dcr", "normal_request"),
    ("zec", "normal_request"),
    ("rvn", "normal_request"),
    ("arweave", "normal_request"),
    ("near", "normal_request"),
    ("qnt", "normal_request"),

    # Возможные попытки SQL-инъекций
    ("SELECT * FROM products WHERE id = 1", "sql_injection_attempt"),
    ("INSERT INTO users (name, email) VALUES ('John', 'john@example.com')", "sql_injection_attempt"),
    ("UPDATE orders SET status = 'shipped' WHERE order_id = 123", "sql_injection_attempt"),
    ("DELETE FROM cart WHERE cart_id = 456", "sql_injection_attempt"),
    ("SELECT * FROM users WHERE age > 25", "sql_injection_attempt"),
    ("SELECT * FROM products WHERE category = 'Electronics'", "sql_injection_attempt"),

    # XSS атаки
    ("<script>Alert('')</script>", "xss"),
    ("<img src=x onerror=alert('XSS')>", "xss"),
    ("<body onload='alert(document.cookie)'>", "xss"),
    ("<iframe src=javascript:alert('XSS')>", "xss"),
    ("<input type=text value=''><script>alert('XSS')</script>", "xss"),
    ("<script>alert('XSS')</script>", "xss"),
    ("<img src='invalid' onerror='alert(\"XSS\")'>", "xss"),
    ("<object data='javascript:alert(\"XSS\")'></object>", "xss"),
    ("<div style='width:expression(alert(\"XSS\"))'></div>", "xss"),
    ("<a href='javascript:alert(\"XSS\")'>Click me</a>", "xss"),
    ("<iframe src='javascript:alert(\"XSS\")'></iframe>", "xss"),
    ("<body onload='alert(\"XSS\")'>", "xss"),
    ("<table><td onclick='alert(\"XSS\")'>Click</td></table>", "xss"),
    ("<marquee onstart='alert(\"XSS\")'>XSS</marquee>", "xss"),
    ("<input type='text' value='XSS' onfocus='alert(\"XSS\")'>", "xss"),
    ("<input type='image' src='x' onerror='alert(\"XSS\")'>", "xss"),
    ("<input type='button' onclick='alert(\"XSS\")'>", "xss"),
    ("<form action='javascript:alert(\"XSS\")'>", "xss"),
    ("<svg><desc><![CDATA[<script>alert(\"XSS\")</script>]]></desc></svg>", "xss"),
    ("<details open><summary>test</summary><script>alert('XSS')</script></details>", "xss"),
    ("<button onclick='alert(\"XSS\")'>XSS</button>", "xss"),
    ("<textarea><script>alert(\"XSS\")</script></textarea>", "xss"),
    ("<style>body:before { content: 'XSS'; }</style>", "xss"),
    ("<p draggable='true' ondragstart='alert(\"XSS\")'>Drag me</p>", "xss"),
    ("<iframe src='data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4='>", "xss"),
    ("<form><button formaction='javascript:alert(\"XSS\")'>Submit</button></form>", "xss"),
    ("<script src='data:text/javascript,alert(\"XSS\")'></script>", "xss"),
    ("<audio src='javascript:alert(\"XSS\")'></audio>", "xss"),
    ("<video><source src='javascript:alert(\"XSS\")'></video>", "xss"),
    ("<svg/onload=alert('XSS')>", "xss"),
    ("<img src='javascript:alert(\"XSS\")'>", "xss"),
    ("<script>document.write('<img src=\"invalid\" onerror=\"alert(\'XSS\')\">');</script>", "xss"),
    ("<script>setTimeout(function() { alert('XSS'); }, 1000);</script>", "xss"),
    ("<script>if(document.cookie) { alert('XSS'); }</script>", "xss"),
    ("<script>var xss = '<img src=\"invalid\" onerror=\"alert(\'XSS\')\">'; document.body.innerHTML += xss;</script>", "xss"),
    ("<script>window.name = '<img src=\"invalid\" onerror=\"alert(\'XSS\')\">'; window.open('about:blank', '_self').document.write(window.name);</script>", "xss"),


    # SQL-инъекции
    ("UNION SELECT username, password FROM users--", "sql_injection"),
    ("' OR 1=1 --", "sql_injection"),
    ("'; DROP TABLE users; --", "sql_injection"),
    ("SELECT * FROM accounts WHERE username = 'admin' --", "sql_injection"),
    ("' OR '1'='1' --", "sql_injection"),
    ("select * from users where username = '' or 1=1 --", "sql_injection"),
    ("' or '' = '", "sql_injection"),
    ("'; drop table products; --", "sql_injection"),
    ("select * from orders where order_id = 0 or order_id = order_id --", "sql_injection"),
    ("' and 1=1; --", "sql_injection"),
    ("' or exists(select * from users where admin=1) --", "sql_injection"),
    ("' or exists(select * from orders where shipped=0) --", "sql_injection"),
    ("union select username, password from admin --", "sql_injection"),
    ("select * from users where username = 'admin' and password = 'password' --", "sql_injection"),
    ("select * from accounts where balance > 0 or '1' = '1' --", "sql_injection"),
    ("select * from users where username = 'john' --", "sql_injection"),
    ("' or '1' = '1' --", "sql_injection"),
    # Другие запросы
    ("<a href='javascript:alert(\"XSS\")'>Click me</a>", "xss"),
    ("' OR '1'='1' --", "sql_injection"),
]
